name: Build gofish on Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Go Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.23.4"

      - name: Build Project
        run: |
          go build -o gofish .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gofish-binary
          path: ./gofish

  notify:
    name: Notify on Build Success
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Send Notification
        run: echo "Build completed successfully for release ${{ github.event.release.tag_name }}."