name: Build and Publish gofish
on:
  release:
    types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.23.4
            - name: Build
              run: go build -o gofish
            - name: Publish
              run: |
                echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
                gh release upload ${{ github.repository }} ${{ github.ref }} gofish